package clients

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"

	"github.com/rs/xlog"
)

const apiKey = "AIzaSyB3U99ctNSn-x2rvk6QhDhJuqnZR9ko7z4"

type LatLong struct {
	Lat float64
	Lon float64
}

type AutoGenerated struct {
	Results []struct {
		AddressComponents []struct {
			LongName  string   `json:"long_name"`
			ShortName string   `json:"short_name"`
			Types     []string `json:"types"`
		} `json:"address_components"`
		FormattedAddress string `json:"formatted_address"`
		Geometry         struct {
			Bounds struct {
				Northeast struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"northeast"`
				Southwest struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"southwest"`
			} `json:"bounds"`
			Location struct {
				Lat float64 `json:"lat"`
				Lng float64 `json:"lng"`
			} `json:"location"`
			LocationType string `json:"location_type"`
			Viewport     struct {
				Northeast struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"northeast"`
				Southwest struct {
					Lat float64 `json:"lat"`
					Lng float64 `json:"lng"`
				} `json:"southwest"`
			} `json:"viewport"`
		} `json:"geometry"`
		PlaceID string   `json:"place_id"`
		Types   []string `json:"types"`
	} `json:"results"`
	Status string `json:"status"`
}

func GetLatLong(address string) (LatLong, error) {
	url := fmt.Sprintf("https://maps.googleapis.com/maps/api/geocode/json?address=%s&key=%s", url.QueryEscape(address), apiKey)
	xlog.Infof("GetLatLong url: %s", url)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return LatLong{}, err
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return LatLong{}, err
	}

	googleResponse := AutoGenerated{}

	if resp.StatusCode == http.StatusOK {
		bodyBytes, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			return LatLong{}, err
		}
		defer resp.Body.Close()

		if err := json.Unmarshal(bodyBytes, &googleResponse); err != nil {
			panic(err)
		}

		if googleResponse.Status == "OK" {
			return LatLong{Lat: googleResponse.Results[0].Geometry.Location.Lat, Lon: googleResponse.Results[0].Geometry.Location.Lng}, nil
		}

		return LatLong{}, fmt.Errorf("error determining lat&lon for addres: %s. status:%s", address, googleResponse.Status)

	}

	return LatLong{}, fmt.Errorf("error determining lat&lon for addres: %s. status: %d", address, resp.StatusCode)
}
